version: '3.8'

services:
  app:
    container_name: jsb-boilerplate-app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/boilerplate
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - APP_SECURITY_JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      - APP_SECURITY_JWT_EXPIRATION=86400000
      - APP_OTP_EXPIRATION=300000
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your-kambing.andro@gmail.com
      - SMTP_PASSWORD=your-app-password
    depends_on:
      - db

  db:
    container_name: psql_primary
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=boilerplate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: